# Generated by Django 2.1.7 on 2019-03-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_category', models.CharField(max_length=255)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_theme', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EventAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('favorite_quote', models.TextField()),
                ('picture_url', models.CharField(default='', max_length=2083)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('is_task_completed', models.BooleanField()),
                ('task_location', models.CharField(max_length=255)),
                ('date_to_complete', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roommate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Roommate')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Task')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Roommate'),
        ),
        migrations.AddField(
            model_name='eventassigned',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Roommate'),
        ),
        migrations.AddField(
            model_name='crew',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Roommate'),
        ),
    ]
