# Generated by Django 2.1.7 on 2019-03-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommate',
            name='avatar_url',
        ),
    ]
