# Generated by Django 2.1.7 on 2019-03-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0002_remove_roommate_avatar_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
