# Generated by Django 2.1.7 on 2019-03-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_auto_20190321_0658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roommate_name', models.CharField(max_length=255)),
                ('bills_for', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roommate_name', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=2083)),
                ('event_theme', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('reward_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roommate_name', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('is_task_completed', models.BooleanField()),
                ('task_location', models.CharField(max_length=255)),
            ],
        ),
    ]
