# Generated by Django 2.1.7 on 2019-03-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0003_auto_20190326_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
