# Generated by Django 2.1.7 on 2019-03-26 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_auto_20190326_0406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventassigned',
            name='event_id',
        ),
        migrations.RemoveField(
            model_name='eventassigned',
            name='roommate',
        ),
        migrations.RemoveField(
            model_name='taskassigned',
            name='roommate',
        ),
        migrations.RemoveField(
            model_name='taskassigned',
            name='task_id',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='EventAssigned',
        ),
        migrations.DeleteModel(
            name='TaskAssigned',
        ),
        migrations.AddField(
            model_name='designated',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Event'),
        ),
        migrations.AddField(
            model_name='designated',
            name='roommate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Roommate'),
        ),
        migrations.AddField(
            model_name='designated',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommates.Task'),
        ),
    ]
