# Generated by Django 2.1.7 on 2019-03-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0004_bill_event_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommate',
            old_name='favorite_quote',
            new_name='favourite_quote',
        ),
    ]
