# Generated by Django 2.1.7 on 2019-04-02 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roommates', '0006_auto_20190331_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_task_completed',
        ),
    ]
